### ISSUE TITLE
Move to cache repositories is not allowed

### ISSUE THREAD

**Issue by marekmrowca** [JFrogDev/jfrog-cli-go#125]
Hi,
I am trying to move artifacts between two remote repositories. 
I tried:
```
jfrog rt mv generic-dev-qaz/ generic-dev-wsx/
jfrog rt mv generic-dev-cvb/* generic-dev-cle/*
```
The result is:
```
[Info] Searching artifacts...
[Info] Found 0 artifacts.
[Info] Moved 0 artifacts.
```

which is not true, because there are artifacts in this repo.

Then I tried:
```
jfrog rt mv generic-dev-qaz-cache/ generic-dev-wsx-cache/
jfrog rt mv generic-dev-qaz-cache/* generic-dev-wsx-cache/*
```

and the result is:
```
[Error] Artifactory response: 409 Conflict
{
  "messages": [
    {
      "level": "ERROR",
      "message": "Failed to move from src=generic-dev-qaz-cache/openvpn to target=generic-dev-wsx-cache/: Target repository generic-dev-wsx-cache is a cache repository. move to cache repositories is not allowed."
    }
...
[Info] Moved 0 artifacts.
[Error] Failed Moving 3 artifacts.
```

How can I move artifacts between two remote repositories?
jfrog version 1.12.1
Artifactory Professional 5.4.6

Best regards,
Marek

**Comment by markgalpin** [comment]
As a general rule you cannot manually deploy artifacts to a remote repository in any way, and this includes copy/move of artifacts to it.  Remote repositories can only have artifacts that are cached from the designated source of the remote repository.

The best practice in this case would be to use a local repository to copy to, and combine it with the remote in a virtual repository that includes both the local and the remote.

So create a repo generic-dev-wsx-local, possibly rename the generic-dev-wsx to generic-dev-wsx-remote
and make a virtual generic-dev-wsx which combines the local and the remote and designates generic-dev-wsx-local the default write target of generic-dev-wsx.

Since the CLI prefers physical repos, then you could 

```jfrog rt mv generic-dev-qaz-cache/* generic-dev-wsx-local```

and the artifacts would then be available through calls to generic-dev-wsx

**Comment by marekmrowca** [comment]
Thank you for reply,
does it mean that remote repositories cannot be renamed?

**Comment by markgalpin** [comment]
In general repositories of any type cannot be renamed in artifactory once they've been created.  The recommended best practice is to create a new repository with the new name.  For local repositories you can then copy/move the artifacts.  For remote repositories just issue a series of head requests against all the objects and/or run some representative builds if you're concerned about re-caching time (because the checksum storage will in most cases not actually require a re-download if the remote provider is providing a checksum) prior to deleting the old one.  Though in general the assumption is that if its in-cache it can just be re-downloaded.

**Comment by eyalbe4** [comment]
Thank you for replying to this question @markgalpin.
@marekmrowca, can this issue be closed?

**Comment by marekmrowca** [comment]
Hi,
yes, I think we can close this issue,
thanks for help!

Best regards

2018-02-18 10:10 GMT+01:00 Eyal Ben Moshe <notifications@github.com>:
