### ISSUE TITLE
Delete empty folders

### ISSUE THREAD

**Issue by mazzy89** [JFrogDev/jfrog-cli-go#154]
In the case I have the a docker image like that

`docker-local/<repo-name>/<image-name>/<image-tag>/manifest.json`

I delete all the files under the image doing this:

`jfrog rt del --quiet=true docker-local/<repo-name>/<image-name>/<image-tag>/*`

However the folder `docker-local/<repo-name>/<image-name>/<image-tag>` will remain empty. How can I clean at the same time also the folder?

Thank you

**Comment by eyalbe4** [comment]
@mazzy89,
The *delete* command can also delete entire Artifactory folders with their content. I think this will work for you:
`jfrog rt del docker-local/<repo-name>/<image-name>`
Let me know if this helps.

**Comment by mazzy89** [comment]
I don't need to remove all the images tag. Under `docker-local/<repo-name>/<image-name>` I have multiple image tags so different images. If I call that command I would remove everything

**Comment by eyalbe4** [comment]
@mazzy89,
If I understand you correctly, you want to delete the *image-tag* folder (with all of its content of course).
So instead of:
`jfrog rt del docker-local/<repo-name>/<image-name>/<image-tag>/*`
do:
`jfrog rt del docker-local/<repo-name>/<image-name>/<image-tag>`
Let me know if this works for you.

**Comment by mazzy89** [comment]
Ok going to try 👍

**Comment by mazzy89** [comment]
It worked. Perfect. thank you. Closing this issue

**Comment by yashwanthiit2009** [comment]
lol
