### ISSUE TITLE
Use patterns or AQL to delete

### ISSUE THREAD

**Issue by jgeorgeson** [JFrogDev/jfrog-cli-go#19]
I have a repo in which I'm uploading expanded P2 software sites built with Maven/Tycho (ie not doing a 'mvn deploy' in the eclipse-repository project to publish the P2 site zip). The basic structure we have within the Artifactory repository is 

`/site/branch/buildNum`

where `site` and `branch` are properties from the pom file and the `buildNum` folder has the format of `YYYYMMDDhhmmss-commitId`. I'm not aware of a Repository Layout I can define to facilitate automatic cleanup of entire `buildNum` folders like Maven artifact SNAPSHOT builds. So I'm looking at the jFrog CLI as an alternative to do manual cleanup. I would to be able to use an AQL expression to delete `buildNum` folders that are "older than X days but keep a minimum of Y instances". But I'd settle for a simple regex like "repo/site1/master/2016(07|080)*/" to delete all the folders under `site1`'s `master` branch starting with 201607 or 2016080.

**Comment by eyalbe4** [comment]
Thanks for sharing this use case @jgeorgeson.
We're planning to add AQL support to the CLI.

**Comment by TamirHadad** [comment]
@jgeorgeson ,
JFrog CLI 1.5.0 includes the capability of using a spec file, by using a spec file you can search artifacts using  AQL.
For more details about the spec option please refer to our [documentation](https://www.jfrog.com/confluence/display/CLI/CLI+for+JFrog+Artifactory#CLIforJFrogArtifactory-UsingFileSpecs).

**Comment by jgeorgeson** [comment]
Thanks! This is a good feature. I notice thought that currently only `upload` supports either AQL and only `download` supports regex. The `delete` command doesn't seem to have gained any new expressive capability using a spec file.

**Comment by eyalbe4** [comment]
Hi @jgeorgeson,
We made a few corrections to the schema documentation for all command. I apologise for that.
The following commands accept AQL (as well as a wildcards pattern) in their File Spec: delete, download, copy, move and search. This is because all of these commands first perform an AQL search to find the files in Artifactory. When one of these commands is used with a wildcards pattern, the pattern is converted to AQL.

The only command which is different is the upload command. Since it needs to find the files to upload on the local file-system, AQL is not relevant. It accepts either wildcards patterns or a regular expressions. Actually, when using the upload command with a wildcards pattern, it converts it to a regular expressions to find and collect the files to be uploaded.

**Comment by jgeorgeson** [comment]
Great! Now I just need to learn AQL!
