### ISSUE TITLE
Feature Request: Support named instances of services so that multiple credentials can be configured

### ISSUE THREAD

**Issue by jgeorgeson** [JFrogDev/jfrog-cli-go#31]
I've only used the CLI to interface with Artifactory, so I don't know if this would make sense for Bintray, MX, or XRay.

Currently in order to use stored credentials I have to rerun the config every time I switch between production and staging servers. While I can use command line arguments such as _--url --user --api-key_ I'd rather have all my instances url/user/key in the config file, and a single _--instance_ option that selects from them.

**Comment by eyalbe4** [comment]
Thank you @jgeorgeson. This is indeed something we plan to add in the future.

**Comment by mcanf** [comment]
This would be a nice feature.  Currently, switching between servers is cumbersome.  Thanks.

**Comment by jgeorgeson** [comment]
In the meantime I have a shell function I use to switch

```
set-jfrog() {
    [ -f ~/.jfrog/jfrog-cli-$1.conf ] || { echo "No config file for \"$1\"."; return; }
    cp ~/.jfrog/jfrog-cli-$1.conf ~/.jfrog/jfrog-cli.conf
}

export -f set-jfrog
```

**Comment by TamirHadad** [comment]
The enhancement of this feature was commited to our dev branch, you can see the [commited code](https://github.com/JFrogDev/jfrog-cli-go/commit/1167651b9ad29d7231975bd10307e451e1980a07 ), build our dev branch and use it.
As part of this enhancement the configuration file has changed, we added a serverName per Artifactory instance configuration and one more field we need in order to get the default server.
To add a new server run: 
`jfrog rt c serverName`
In order to set a server to work with use :
`jfrog rt c use serverName`
To list all the servers use :
`jfrog rt c show`

In addition, each of the Artifactory commands now has an additional flag --server-name.

please notice, this is not our final version and things can be change later on.
Once you use this version the configuration file will be changed so older versions of the cli won't be able to use it.

**Comment by eyalbe4** [comment]
@jgeorgeson,
Version 1.8.0 has been recently released, and supports configuring multiple Artifactory instances using the *jfrog rt config* command. You can then switch between your configured Artifactory servers using the *jfrog rt use* command, or alternatively pass the *--server-id* option to the CLI Artifactory commands.

**Comment by jgeorgeson** [comment]
Nice! I'm having a little trouble with it though. I ran `jfrog rt c` for each of my servers, and the resulting `~/.jfrog/jfrog-cli.conf` only contains the last server I ran the config for. If I manually set each instance in `~/.jfrog/jfrog-cli.conf` then I can select the instance with `jfrog rt use`. Is there a way to print the current default server ID without looking at the conf file?

**Comment by eyalbe4** [comment]
Hi @jgeorgeson,
The *jfrog rt c* command can now receive an optional argument with the server ID value.
For example, running *jfrog rt c rt-1* configures a new server with *rt-1* as its server ID.
If you'd like *rt-1* to become the default server, you'll then need to run *jfrog rt use rt-1*.
Running *jfrog rt c* without specifying a server ID overrides the configurrd default server.
Please let us know if this helps and resolves the issue.

**Comment by jgeorgeson** [comment]
Ok. I was expecting the config command's documentation to be at the top of the [page](https://www.jfrog.com/confluence/display/CLI/CLI+for+JFrog+Artifactory) so I didn't see it at first. Everything appears to be working as documented now. Thanks.
