### ISSUE TITLE
Cannot use regexp for rt upload

### ISSUE THREAD

**Issue by rinrinne** [JFrogDev/jfrog-cli-go#47]
Version: 1.8.0

command essential:
$ jfrog rt upload --spec=upload.spec

upload.spec
```
{
  "files": [
    {
      "pattern": ".*",
      "target": "local-repo/",
      "regexp" : "true"
    }
  ]
}
```
Result:
```
[Error] Path does not exist: .*
```

Seems jfrog try to get rootPath from pattern. I cannot find any document for regexp in spec file.

I would like to suggest to remove regexp support in pattern attribute. Instead, add new attribute, e.g. "filter", which is applied against resolved file set.

**Comment by eyalbe4** [comment]
@rinrinne,
Adding parenthesis to the *pattern* will resolve the issue for you:
```
{
  "files": [
    {
      "pattern": "(.*)",
      "target": "local-repo/",
      "regexp" : "true"
    }
  ]
}
```
In the documentation for *upload* command, the *Source path* argument description includes the following comment:
If you have specified that you are using regular expressions, then the first one used in the argument must be enclosed in parenthesis.

In order to determine the root path, the CLI searcher for the first parenthesis in the regular expression. We will soon add an example for using regular expressions and perhaps also add this comment to the *--regexp* option description.
The *filter* suggestion is interesting through. We'll consider adding a filtering mechanism of some sort in the future.

**Comment by rinrinne** [comment]
Thanks for prompt reply.

Oh, I missed such mention in Source path... OK, I will write pattern using parenthesis.

And I'm glad to your positive answer regarding my suggestion:smile:
Thanks a lot!!
