### ISSUE TITLE
Proxy Issue?

### ISSUE THREAD

**Issue by hackily** [JFrogDev/jfrog-cli-go#67]
I'm on Ubuntu 16.07, and I'm trying to run this cli in a docker environment, but I'm running into proxy problems, and only when trying to configure the CLI.
My command:
```
RUN go get github.com/jfrogdev/jfrog-cli-go/jfrog \
    && cd /tmp \
    && $GOPATH/bin/jfrog rt dl --url="https://company.com/artifactory" --user="<username>" --password="<password>" "XBKLI/Packages/" \

The CLI commands require the Artifactory URL and authentication details
Configuring JFrog CLI with these parameters now will save you having to include them as command options.
You can also configure these parameters later using the 'config' command.
Configure now? (y/n): [Info] Searching items to download...
y
[Error] Post https://company.com/artifactory/api/search/aql: dial tcp companyip:443: getsockopt: connection timed out
```

What's puzzling is that I can 

```
RUN echo ${no_proxy}
RUN echo ${http_proxy}
RUN echo ${https_proxy}
```

just fine, and I get the correct proxies. 
I also have a file that sets up my docker environment settings with the correct proxies:
/etc/systemd/system/docker.service.d/http-proxy.conf

Any pointers as to why the proxy settings aren't being picked up/used would be very helpful!

**Comment by eyalbe4** [comment]
@hackily,
My apologies for the late response.
JFrog CLI does not yet support picking up and using a proxy server when interacting with Artifactory. This is something we're planning to add soon.
We'll make sure to keep you posted.

**Comment by neechbear** [comment]
Is there any timeline for adding support for HTTP proxy support?

I have dozens of projects that I would much rather not generate our own build JSON files to upload builds to Artifactory with. The `jfrog-cli` tool is a much better solution for our use case, but we cannot use it because we depend on `http_proxy` support inside our build environments.

I imagine this is similar in many other large enterprise build environments, as it is a common security consideration.

**Comment by eyalbe4** [comment]
@neechbear and @hackily
Version 1.11.1 supports the http_proxy environment variable. Please try configuring it and let us if you manage to route the CLI's outgoing Artifactory traffic through your proxy server.

**Comment by jgsuess** [comment]
That 1.11.1 fix now leads to confusion because `no_proxy` is not honoured. Could you just use libproxy https://github.com/libproxy/libproxy ? Then you would not need this painful tinkering with resolution...

**Comment by eyalbe4** [comment]
@jgsuess,
Thanks for letting us know about this.
We'll soon make sure **no_proxy** is honoured by the CLI and update this issue once done. As for https://github.com/libproxy/libproxy it looks like there's no license added to this repository, so I'm not sure we can use it.

**Comment by jgsuess** [comment]
Please see the GPL copy here, as customary.
https://github.com/libproxy/libproxy/blob/master/COPYING

**Comment by yahavi** [comment]
@jgsuess,
The JFrog CLI uses the native golang http module in order to handle proxy settings, including the no_proxy handling.
 
Can you specify the structure of your "no_proxy" value? Is it Artifactory's IP? 

And what is your OS?
I tried on "Ubuntu 17.10" and "MacOS High Sierra 10.13.3" and the problem didn't reproduce.

**Comment by jgsuess** [comment]
The no_proxy value is a comma-seperate list of DNS domain and server names.

The OSS are Ubuntu 16.04 LTS and Oracle Linux 6 and 7.
